---
blacklist:
  - GPL-2.0

whitelist:
  - Apache-2.0
  - BSD-2-Clause
  - BSD-3-Clause
  - ISC
  - LGPL-3.0
  - MIT
  - MPL-2.0

exceptions:
  - bitbucket.org/ww/goautoneg # BSD-3-Clause, license is in the source, misdetected as Apache-2.0
  - github.com/munnerz/goautoneg # BSD-3-Clause, license is in the source
  - github.com/opencontainers/go-digest # Apache-2.0
